prompt_template_name: alpaca_short
model_type: AudioMosaic-LTU
audio_encoder_path: experiments/AudioMosaic/pretrain/checkpoints/model_state_dict.pt
base_model: checkpoints/ltu_pretrained_mdls
model_path: experiments/AudioMosaic/stage3_all_closed/checkpoints/checkpoint-7000/pytorch_model.bin
data_path: /PATH/TO/datasets/openaqa/data/openaqa_5.6M_prep.json
batch_size: 256
micro_batch_size: 32
num_epochs: 1
learning_rate: 1.e-4
cutoff_len: 108
val_set_size: 0
lora_r: 8
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules: 
  - q_proj
  - v_proj
train_on_inputs: true
group_by_length: true 
save_steps: 1000
trainable_params: all
resume_from_checkpoint: false
